# Decision tree

In [1]:
import pandas as pd
import numpy as np

In [2]:
car_data=pd.read_csv(r'C:\Users\hp\DT\cars.csv',header=0)
car_data.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [3]:
car_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [4]:
car_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    med   unacc
1  vhigh  vhigh     2       2    small   high   unacc
2  vhigh  vhigh     2       2      med    low   unacc
3  vhigh  vhigh     2       2      med    med   unacc
4  vhigh  vhigh     2       2      med   high   unacc

In [5]:
car_data.isnull().sum()#no missing value to be handle and hence decision tree is not affected by the outlier

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [6]:
car_df=pd.DataFrame.copy(car_data)

In [7]:
colname=car_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [8]:
from sklearn import preprocessing


le=preprocessing.LabelEncoder()

for x in colname:
    car_df[x]=le.fit_transform(car_df[x])

In [9]:
car_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       2        2
1       3      3      0        0         2       0        2
2       3      3      0        0         1       1        2
3       3      3      0        0         1       2        2
4       3      3      0        0         1       0        2

In [10]:
car_data.classes.value_counts()
#acc==>0
#good==>1
#unacc==>2
#vgood==>3

unacc    1209
acc       384
good       69
vgood      65
Name: classes, dtype: int64

In [11]:
X=car_df.values[:,:-1]
Y=car_df.values[:,-1]
Y=Y.astype(int)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)   

X=scaler.transform(X) 



In [13]:
from sklearn.model_selection import train_test_split
#split the data into test and train
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.3, random_state=10)

# Running of decision tree

In [14]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="gini",
random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [15]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[114   0   6   3]
 [  0  15   0   1]
 [  5   0 353   0]
 [  3   0   0  19]]
0.9653179190751445
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       123
           1       1.00      0.94      0.97        16
           2       0.98      0.99      0.98       358
           3       0.83      0.86      0.84        22

    accuracy                           0.97       519
   macro avg       0.94      0.93      0.93       519
weighted avg       0.97      0.97      0.97       519



In [17]:
print(list(zip(car_df.columns,model_DecisionTree.feature_importances_)))

[('buying', 0.2052617604130662), ('maint', 0.19572990696085116), ('doors', 0.045241276636712166), ('persons', 0.1829750936240389), ('lug_boot', 0.1131611528888087), ('safety', 0.2576308094765229)]


In [18]:
from sklearn import tree
with open("model_DecisionTree.txt", "w") as f:

    f = tree.export_graphviz(model_DecisionTree, feature_names=car_df.columns[:-1],
                            out_file=f)

#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [19]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="gini",max_depth=10, min_samples_leaf=5,
random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [20]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[112   7   4   0]
 [  0  16   0   0]
 [ 19   0 339   0]
 [  4   2   0  16]]
0.930635838150289
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       123
           1       0.64      1.00      0.78        16
           2       0.99      0.95      0.97       358
           3       1.00      0.73      0.84        22

    accuracy                           0.93       519
   macro avg       0.86      0.90      0.86       519
weighted avg       0.94      0.93      0.93       519



In [22]:
from sklearn import svm
classifier=svm.SVC(kernel="rbf", gamma=0.1, C=50)
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[119   2   2   0]
 [  0  16   0   0]
 [  6   0 352   0]
 [  1   0   0  21]]
0.9788053949903661
              precision    recall  f1-score   support

           0       0.94      0.97      0.96       123
           1       0.89      1.00      0.94        16
           2       0.99      0.98      0.99       358
           3       1.00      0.95      0.98        22

    accuracy                           0.98       519
   macro avg       0.96      0.98      0.97       519
weighted avg       0.98      0.98      0.98       519



In [24]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 37   0  86   0]
 [ 10   2   4   0]
 [  1   0 357   0]
 [  7   0   9   6]]
0.7745664739884393
              precision    recall  f1-score   support

           0       0.67      0.30      0.42       123
           1       1.00      0.12      0.22        16
           2       0.78      1.00      0.88       358
           3       1.00      0.27      0.43        22

    accuracy                           0.77       519
   macro avg       0.86      0.42      0.49       519
weighted avg       0.77      0.77      0.73       519



In [26]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 29   0  94   0]
 [  1   0  15   0]
 [ 20   0 338   0]
 [ 11   0  11   0]]
0.7071290944123314
              precision    recall  f1-score   support

           0       0.48      0.24      0.32       123
           1       0.00      0.00      0.00        16
           2       0.74      0.94      0.83       358
           3       0.00      0.00      0.00        22

    accuracy                           0.71       519
   macro avg       0.30      0.29      0.29       519
weighted avg       0.62      0.71      0.65       519



C:\Users\hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [28]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier

model=ExtraTreesClassifier(100, random_state=10)


#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

In [29]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[112   7   4   0]
 [  0  16   0   0]
 [ 19   0 339   0]
 [  4   2   0  16]]
0.930635838150289
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       123
           1       0.64      1.00      0.78        16
           2       0.99      0.95      0.97       358
           3       1.00      0.73      0.84        22

    accuracy                           0.93       519
   macro avg       0.86      0.90      0.86       519
weighted avg       0.94      0.93      0.93       519



In [31]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=100,max_depth=8, min_samples_leaf=10, random_state=100)


#fit the model on the data and predict the values
model_RandomForest=model.fit(X_train,Y_train)


In [32]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[112   7   4   0]
 [  0  16   0   0]
 [ 19   0 339   0]
 [  4   2   0  16]]
0.930635838150289
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       123
           1       0.64      1.00      0.78        16
           2       0.99      0.95      0.97       358
           3       1.00      0.73      0.84        22

    accuracy                           0.93       519
   macro avg       0.86      0.90      0.86       519
weighted avg       0.94      0.93      0.93       519



In [34]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10), n_estimators=10,random_state=100)


#fit the model on the data and predict the values
model_RandomForest=model.fit(X_train,Y_train)

In [35]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[112   7   4   0]
 [  0  16   0   0]
 [ 19   0 339   0]
 [  4   2   0  16]]
0.930635838150289
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       123
           1       0.64      1.00      0.78        16
           2       0.99      0.95      0.97       358
           3       1.00      0.73      0.84        22

    accuracy                           0.93       519
   macro avg       0.86      0.90      0.86       519
weighted avg       0.94      0.93      0.93       519



In [37]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier( n_estimators=10,random_state=100)


#fit the model on the data and predict the values
model_RandomForest=model.fit(X_train,Y_train)

In [38]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[112   7   4   0]
 [  0  16   0   0]
 [ 19   0 339   0]
 [  4   2   0  16]]
0.930635838150289
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       123
           1       0.64      1.00      0.78        16
           2       0.99      0.95      0.97       358
           3       1.00      0.73      0.84        22

    accuracy                           0.93       519
   macro avg       0.86      0.90      0.86       519
weighted avg       0.94      0.93      0.93       519



In [43]:
from xgboost import XGBClassifier

model_GradientBoosting=XGBClassifier(random_state=100)


#fit the model on the data and predict the values
model_RandomForest=model.fit(X_train,Y_train)

In [44]:
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[112   7   4   0]
 [  0  16   0   0]
 [ 19   0 339   0]
 [  4   2   0  16]]
0.930635838150289
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       123
           1       0.64      1.00      0.78        16
           2       0.99      0.95      0.97       358
           3       1.00      0.73      0.84        22

    accuracy                           0.93       519
   macro avg       0.86      0.90      0.86       519
weighted avg       0.94      0.93      0.93       519



In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=8, metric='euclidean')
estimators.append(('knn', model4))


# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[120   0   3   0]
 [  2  14   0   0]
 [  6   0 352   0]
 [  4   0   0  18]]
0.9710982658959537
              precision    recall  f1-score   support

           0       0.91      0.98      0.94       123
           1       1.00      0.88      0.93        16
           2       0.99      0.98      0.99       358
           3       1.00      0.82      0.90        22

    accuracy                           0.97       519
   macro avg       0.98      0.91      0.94       519
weighted avg       0.97      0.97      0.97       519



In [48]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

# create the sub models
estimators = []
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=8, metric='euclidean')
estimators.append(('knn', model4))


# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[120   0   3   0]
 [  1  15   0   0]
 [  5   0 353   0]
 [  3   0   0  19]]
0.976878612716763
              precision    recall  f1-score   support

           0       0.93      0.98      0.95       123
           1       1.00      0.94      0.97        16
           2       0.99      0.99      0.99       358
           3       1.00      0.86      0.93        22

    accuracy                           0.98       519
   macro avg       0.98      0.94      0.96       519
weighted avg       0.98      0.98      0.98       519

